[View in Colaboratory](https://colab.research.google.com/github/khandelwal1998/Acadview-Assignments/blob/master/Assignment_29thMay.ipynb)

**Question1**

In [0]:
import numpy as np

In [0]:
x=np.random.randn(10,1)

In [5]:
x

array([[-0.46615581],
       [-1.76483951],
       [ 0.08109528],
       [-0.63450537],
       [ 2.22038864],
       [-1.18888404],
       [ 1.45256221],
       [ 0.13940102],
       [ 0.27438185],
       [-0.14355573]])

In [7]:
x.mean()

-0.0030111457333806073

**Question 2**

In [0]:
y=np.random.randn(20,1)

In [10]:
y

array([[-0.80874806],
       [-0.54865362],
       [-0.43394973],
       [-0.04724139],
       [-1.57877487],
       [ 0.67886653],
       [-0.54894328],
       [ 0.67165568],
       [ 2.07849318],
       [-1.59457835],
       [ 1.35782261],
       [ 0.18384831],
       [-1.4459606 ],
       [-1.20650868],
       [ 0.61697321],
       [-1.37637236],
       [-0.2096444 ],
       [ 0.57235388],
       [-0.64224379],
       [ 0.9487462 ]])

In [0]:
variance=y.var()

In [0]:
  sd=y.std()

In [26]:
'variance:' ,variance

('variance:', 1.0271022660160298)

In [28]:
print("standard deviation: ",sd)

('standard deviation: ', 1.013460539940273)


**Question 3**

In [0]:
A=np.random.randn(10,20)
B=np.random.randn(20,25)

In [34]:
c=np.dot(A,B)
print(c)

[[-9.04469140e+00 -3.05907411e+00  4.28962489e-01 -3.98406128e+00
  -2.16260253e+00 -2.31739574e+00 -7.40377065e-01 -4.23275039e+00
   6.86822045e-01 -5.31090883e+00 -3.44722443e-01  1.36063312e+00
   1.85900948e-01  9.86433944e-01  1.68084158e+00 -5.31770894e+00
   7.26569461e+00 -1.10546139e+00 -2.39148247e+00  5.19664560e+00
  -1.30579131e+00  1.18465411e-02  2.37427071e+00 -6.98598291e-01
   2.77324294e+00]
 [-9.53106762e+00  1.87546400e+00  1.96069972e+00 -6.89020808e-01
  -1.72445904e+00 -2.63023615e+00  2.70922297e+00  4.72069506e+00
   2.01928404e+00  3.42553475e-01  2.04522274e+00  2.28273487e-01
  -7.01501197e-01  2.37132236e-01  9.62933116e-01 -2.40200934e+00
  -2.52410921e+00  2.36326907e-01  2.37188957e+00 -2.44577147e+00
   1.57472547e-01 -4.72467149e-01  3.12996636e+00 -9.13272366e-01
   1.76506510e+00]
 [-3.84472846e+00  6.63852345e+00  2.88791491e+00  2.02722756e+00
  -3.05328446e+00 -2.12406119e+00  1.51364983e+00  4.72883473e+00
   4.77339008e+00 -1.56191869e+00 -7.8

In [37]:
sum(sum(c))

-72.285027817186

**Question 4**

In [40]:
A=np.random.randn(10,1)
B=1/(1+np.exp(-A))
print(A)
print("\n")
print(B)

[[ 0.72546176]
 [-0.22391753]
 [ 1.44874533]
 [-0.43736052]
 [ 0.38796777]
 [ 0.08779881]
 [ 1.00015781]
 [ 0.13094741]
 [-0.29407003]
 [ 1.19088672]]


[[0.6738086 ]
 [0.44425335]
 [0.80980526]
 [0.39237008]
 [0.59579339]
 [0.52193561]
 [0.7310896 ]
 [0.53269015]
 [0.42700775]
 [0.76689962]]
